import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { RequestOrbit } from "@/components/DayflowMotion";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, CheckCheck, ClipboardList, Loader2, Send, ShieldAlert } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

type RequestStatus = "open" | "in_progress" | "resolved" | "closed";
type RequestType = "document" | "access" | "policy" | "support";

const labels: Record<RequestType, string> = { document: "Document", access: "Access", policy: "Policy", support: "Support" };
const statusLabels: Record<RequestStatus, string> = { open: "Open", in_progress: "In progress", resolved: "Resolved", closed: "Closed" };
const formatDate = (timestamp: number) => new Date(timestamp).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });

function StatusPill({ status }: { status: RequestStatus }) {
  const tone = status === "resolved" || status === "closed" ? "sage" : status === "in_progress" ? "navy" : "saffron";
  return <span className={`status-pill status-pill--${tone}`}>{statusLabels[status]}</span>;
}

export default function RequestsCenter() {
  const { user, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const mine = trpc.hr.myRequests.useQuery(undefined, { enabled: isAuthenticated });
  const team = trpc.hr.adminRequests.useQuery(undefined, { enabled: isAuthenticated && user?.role === "admin" });
  const [requestType, setRequestType] = useState<RequestType>("support");
  const [priority, setPriority] = useState<"standard" | "high">("standard");
  const [subject, setSubject] = useState("");
  const [details, setDetails] = useState("");
  const [adminDrafts, setAdminDrafts] = useState<Record<number, { status: RequestStatus; resolution: string }>>({});
  const refresh = async () => { await Promise.all([utils.hr.myRequests.invalidate(), utils.hr.adminRequests.invalidate()]); };
  const createRequest = trpc.hr.createRequest.useMutation({
    onSuccess: async () => { await refresh(); setSubject(""); setDetails(""); setPriority("standard"); toast.success("Request sent", { description: "Dayflow has added it to the right queue." }); },
    onError: error => toast.error(error.message),
  });
  const updateRequest = trpc.hr.updateRequest.useMutation({ onSuccess: async () => { setAdminDrafts({}); await refresh(); toast.success("Request updated", { description: "The employee can now see the latest status and response." }); }, onError: error => toast.error(error.message) });
  const openCount = useMemo(() => mine.data?.filter(item => item.status === "open" || item.status === "in_progress").length ?? 0, [mine.data]);
  const submit = (event: FormEvent) => { event.preventDefault(); createRequest.mutate({ requestType, priority, subject, details }); };
  const isLoading = mine.isLoading || (user?.role === "admin" && team.isLoading);
  const hasError = mine.isError || (user?.role === "admin" && team.isError);

  return <DashboardLayout><div className="request-center mx-auto max-w-6xl pb-14 pt-2"><header className="request-center__header"><div><p className="eyebrow">Action center</p><h1 className="mt-2 font-[DM_Serif_Display] text-4xl tracking-[-0.045em] text-[#172336]">Make the next move clear.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#65717d]">Submit one focused HR request, track its status, and keep every response in a single shared record.</p></div><div className="request-center__signal"><RequestOrbit state={openCount ? "active" : "clear"} count={openCount} /><div><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-[#75818d]">Your queue</p><p className="mt-1 font-[DM_Serif_Display] text-3xl tracking-[-0.04em]">{openCount} active</p></div></div></header>
    {hasError ? <section className="tool-error-state"><ShieldAlert className="h-7 w-7 text-[#c98708]" /><div><p className="eyebrow">Connection paused</p><h2 className="mt-2 font-[DM_Serif_Display] text-3xl">Requests could not load.</h2><p className="mt-2 text-sm text-[#65717d]">No changes have been made. Retry when the secure data connection is available.</p><Button onClick={() => { mine.refetch(); team.refetch(); }} className="dayflow-button mt-4 rounded-full px-5 text-xs">Retry request center</Button></div></section> : isLoading ? <div className="grid min-h-80 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#c98708]" /></div> : <div className="request-center__grid"><section className="request-composer"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">New request</p><h2 className="mt-2 font-[DM_Serif_Display] text-3xl tracking-[-0.04em]">Tell us what would help.</h2></div><ClipboardList className="h-6 w-6 text-[#c98708]" /></div><form onSubmit={submit} className="mt-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-extrabold">Request type<select value={requestType} onChange={event => setRequestType(event.target.value as RequestType)} className="tool-input mt-1.5"><option value="support">Support</option><option value="document">Document</option><option value="access">Access</option><option value="policy">Policy</option></select></label><label className="text-xs font-extrabold">Priority<select value={priority} onChange={event => setPriority(event.target.value as "standard" | "high")} className="tool-input mt-1.5"><option value="standard">Standard</option><option value="high">High</option></select></label><label className="text-xs font-extrabold sm:col-span-2">Subject<input required minLength={3} maxLength={160} value={subject} onChange={event => setSubject(event.target.value)} placeholder="What do you need?" className="tool-input mt-1.5" /></label><label className="text-xs font-extrabold sm:col-span-2">Context<textarea required minLength={5} maxLength={1200} value={details} onChange={event => setDetails(event.target.value)} placeholder="Add the details that will help HR respond without extra follow-up." className="tool-input mt-1.5 min-h-32" /></label></div><div className="mt-5 flex items-center justify-between gap-3"><p className="max-w-xs text-xs leading-5 text-[#75818d]">Your request stays visible to you and the Admin / HR team.</p><Button disabled={createRequest.isPending} className="dayflow-button shrink-0 rounded-full px-5 text-xs"><Send className="h-3.5 w-3.5" />{createRequest.isPending ? "Sending…" : "Send request"}</Button></div></form></section>
      <section className="request-panel"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow">Your requests</p><h2 className="mt-2 font-[DM_Serif_Display] text-3xl tracking-[-0.04em]">The record, in one view.</h2></div><span className="request-panel__count">{mine.data?.length ?? 0}</span></div><div className="mt-5 space-y-3">{mine.data?.length ? mine.data.map(item => <article key={item.id} className="request-card"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="request-card__type">{labels[item.requestType]}</span>{item.priority === "high" && <span className="request-card__priority">High attention</span>}</div><h3 className="mt-2 text-sm font-extrabold text-[#172336]">{item.subject}</h3><p className="mt-1 text-xs leading-5 text-[#687483]">{item.details}</p></div><StatusPill status={item.status} /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[#172336]/8 pt-3 text-[11px] font-bold text-[#7b8792]"><span>{formatDate(item.createdAt.getTime())}</span>{item.resolution ? <span className="inline-flex items-center gap-1 text-[#385442]"><CheckCheck className="h-3.5 w-3.5" />Response available</span> : <span>Awaiting response</span>}</div>{item.resolution && <p className="request-card__response">{item.resolution}</p>}</article>) : <article className="request-empty"><RequestOrbit state="clear" count={0} /><div><p className="eyebrow">A calm queue</p><h3 className="mt-2 font-[DM_Serif_Display] text-3xl tracking-[-0.04em]">Nothing needs follow-up yet.</h3><p className="mt-2 text-sm text-[#65717d]">Use the form to create your first HR request.</p></div></article>}</div></section>
    </div>}
    {user?.role === "admin" && !hasError && <section className="request-admin-panel mt-6"><div className="request-admin-panel__heading"><div><p className="eyebrow">Admin / HR queue</p><h2 className="mt-2 font-[DM_Serif_Display] text-3xl tracking-[-0.04em]">Resolve with context, not guesswork.</h2></div><p className="max-w-xs text-sm leading-6 text-[#687483]">Update a request in place. Employees immediately see the new status and final response.</p></div><div className="mt-5 grid gap-3">{team.data?.length ? team.data.map(item => { const draft = adminDrafts[item.id] ?? { status: item.status, resolution: item.resolution ?? "" }; return <article key={item.id} className="admin-request-card"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="request-card__type">{labels[item.requestType]}</span><span className="text-xs font-bold text-[#687483]">{item.employeeName} · {item.employeeCode}</span></div><h3 className="mt-2 text-base font-extrabold">{item.subject}</h3><p className="mt-1 text-sm leading-6 text-[#65717d]">{item.details}</p></div><div className="admin-request-card__actions"><select value={draft.status} onChange={event => setAdminDrafts(previous => ({ ...previous, [item.id]: { ...draft, status: event.target.value as RequestStatus } }))} disabled={updateRequest.isPending} className="tool-input"><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><textarea value={draft.resolution} onChange={event => setAdminDrafts(previous => ({ ...previous, [item.id]: { ...draft, resolution: event.target.value } }))} placeholder="Add a response before resolving." className="tool-input min-h-20" /><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-bold text-[#7b8792]">Created {formatDate(item.createdAt.getTime())}</span><Button onClick={() => updateRequest.mutate({ requestId: item.id, status: draft.status, resolution: draft.resolution || undefined })} disabled={updateRequest.isPending} className="dayflow-button rounded-full px-4 py-2 text-[11px]">{updateRequest.isPending ? "Saving…" : "Save update"}</Button></div></div></article>; }) : <article className="request-empty request-empty--team"><RequestOrbit state="clear" count={0} /><div><p className="eyebrow">Team queue clear</p><h3 className="mt-2 font-[DM_Serif_Display] text-3xl tracking-[-0.04em]">No requests to resolve.</h3><p className="mt-2 text-sm text-[#65717d]">New employee requests will appear here with the full context.</p></div></article>}</div></section>}
  </div></DashboardLayout>;
}
